sudo: required
services:
    - docker

env:
    global:
        - SHA=$(git rev-parse HEAD)
        - CLOUDSKD_CORE_DISABLE_PROMPTS=1

before_install:
# Decrypt service accound credentials
    - openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypted_0c35eebf403c_iv -in service-account.json.enc -out service-account.json -d
# Install Google Cloud CTL
    - curl https://sdk.cloud.google.com | bash > /dev/null;
    - source $HOME/google-cloud-sdk/path.bash.inc
    - gcloud components update kubectl
    - gcloud auth activate-service-account --key-file service-account.json
    - gcloud config set project authentic-realm-263520
    - gcloud config set compute/zone europe-north1-a
    - gcloud container clusters get-credentials multi-cluster
# Log in to docker cli
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Build client app for tests
    - docker build -t infine/react-test -f ./client/Dockerfile.dev ./client

script:
# Run client tests
    - docker run -e CI=true infine/react-test npm run test

deploy:
    provider: script
    script:  bash ./deploy.sh
    on:
        branch: master