apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer

metadata:
  name: letsencrypt-prod

spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/direcory
    email: 'infine@dasuppa.com'
    privateKeyRef:
      name: letsencrypt-prod
    http01: {}